import axios from 'axios';
import type { Task } from '@/components/task-manage/task-type';

const JSON_SERVER_URL =
  process.env.NEXT_PUBLIC_JSON_SERVER_URL || 'http://localhost:3001';

const api = axios.create({
  baseURL: JSON_SERVER_URL,
  timeout: 6000,
  headers: { 'Content-Type': 'application/json' },
});

/** Fetch all tasks from JSON Server */
export async function getTasks(): Promise<Task[]> {
  const { data } = await api.get<Task[]>('/tasks');
  return data;
}

/** Create a task. Id is auto-generated by JSON Server. */
export async function createTask(
  body: Omit<Task, 'id'>
): Promise<Task> {
  const { data } = await api.post<Task>('/tasks', body);
  return data;
}

/** Delete a task */
export async function deleteTask(id: number): Promise<void> {
  await api.delete(`/tasks/${id}`);
}

/** Update a task */
export async function updateTask(id: number, body: Partial<Task>): Promise<Task> {
  const { data } = await api.put<Task>(`/tasks/${id}`, body);
  return data;
}